names:
  piesport: &piesport 'Pis port'
  bks: &bks 'Bernkastel Kuuhs'
  morbach: &morbach 'Morbach'
  thalfang: &thalfang 'Thalfang'

snippets:
  notfall: &notfall >-
    <p>
      <s>In dringenden Notfällen erreichen sie den Notdienst unter <prosody rate="80%"><say-as interpret-as="verbatim">0173</say-as><break time="500ms" strength="x-weak"/><say-as interpret-as="verbatim">30</say-as><break time="500ms"/><say-as interpret-as="verbatim">11</say-as><break time="500ms"/><say-as interpret-as="verbatim">555</say-as></prosody>.</s>
      <s>Ich wiederhole:<break time="1s" strength="x-weak"/> <prosody rate="80%"><say-as interpret-as="verbatim">0173</say-as><break time="500ms" strength="x-weak"/><say-as interpret-as="verbatim">30</say-as><break time="500ms"/><say-as interpret-as="verbatim">11</say-as><break time="500ms"/><say-as interpret-as="verbatim">555</say-as></prosody>.</s>
      <s>Ansonsten können sie nach dem Signalton eine Nachricht hinterlassen, wir rufen sie schnellst möglich zurück.</s>
    </p>
    

templates:
  voice-defaults: &voice-defaults
    gender: female
    language: de-DE
    voice: de-DE-Wavenet-C
    encoding: mp3

  normal: &closed
    <<: *voice-defaults
    input: >-
      <speak>
        <p>
          <s>Guten Tag!</s>
          <s>Sie sind mit dem Sanitätshaus Schichtel in {{name}} verbunden.</s>
          <s>Leider rufen Sie außerhalb unserer Geschäftszeiten an.</s>
          {{opening-hours}}
          <s>An Wochenenden haben wir nicht geöffnet.</s>
        </p>
        {{notfall}}
      </speak>
  busy: &busy
    <<: *voice-defaults
    input: >-
      <speak>
        <p>
          <s>Hallo und herzlich Willkommen beim Sanitätshaus Schichtel in {{name}}.</s>
          <s>Im Augenblick sind alle Leitungen belegt.</s>
          <s>Gerne können Sie uns jetzt nach dem Signalton eine Nachricht hinterlassen, wir rufen Sie dann schnellstmöglich zurück!</s>
        </p>
      </speak>
  christmas: &christmas
    <<: *voice-defaults
    input: >-
      <speak>
        <p>
          <s>Guten Tag!</s>
          <s>Sie sind mit dem Sanitätshaus Schichtel verbunden.</s>
          <s>Leider rufen Sie außerhalb unserer Geschäftszeiten an.</s>
          <s>
            Diese sind vom <say-as interpret-as="date" format="mm-dd" detail="1">12-23</say-as> bis einschließlich zum <say-as interpret-as="date" format="mm-dd" detail="1">12-31</say-as> in allen Filialen werktags von <say-as interpret-as="time">09:00</say-as> bis <say-as interpret-as="time">13:00</say-as>.
          </s>
        </p>
        {{notfall}}
      </speak>
  rosenmontag: &fastnacht
    <<: *voice-defaults
    input: >-
      <speak>
        <p>
          <s>Guten Tag!</s>
          <s>Sie sind mit dem Sanitätshaus Schichtel verbunden.</s>
          <s>Leider rufen Sie außerhalb unserer Geschäftszeiten an.</s>
          <s>Diese sind am Weiberdonnerstag von <say-as interpret-as="time">09:00</say-as> bis <say-as interpret-as="time">15:00</say-as>.</s>
          <s>An Rosenmontag und Fastnachtsdienstag haben wir nicht geöffnet.</s>
        </p>
        {{notfall}}
      </speak>
  krankheit-geschlossen: &krankheit-geschlossen
    <<: *voice-defaults
    input: >-
      <speak>
        <p>
          <s>Guten Tag!</s>
          <s>Sie sind mit dem Sanitätshaus Schichtel verbunden.</s>
          <s>Wegen mehreren Krankheitsfällen ist unsere Filiale {{name}} bis auf weiteres nur Vormittags geöffnet.</s> 
          <s>Wir bitten um ihr Verständnis.</s>
        </p>
        {{notfall}}
      </speak>

texts:
  'Weihnachten':
    <<: *christmas
    variables:
      notfall: *notfall
  'Fastnacht':
    <<: *fastnacht
    variables:
      notfall: *notfall
  'Piesport-geschlossen':
    <<: *closed
    variables:
      name: *piesport
      notfall: *notfall
      opening-hours: &piesport-opening-ours >-
        <s>Diese sind von Montag bis Freitag von <say-as interpret-as="time">09:00</say-as> bis <say-as interpret-as="time">13:00</say-as> und von <say-as interpret-as="time">14:00</say-as> bis <say-as interpret-as="time">18:00</say-as>.</s>
        <s>Mittwochs ist durchgehend von <say-as interpret-as="time">09:00</say-as> bis <say-as interpret-as="time">15:00</say-as> geöffnet.</s>

  'Bernkastel-Kues-geschlossen':
    <<: *closed
    variables:
      name: *bks
      notfall: *notfall
      opening-hours: *piesport-opening-ours
  'Morbach-geschlossen':
    <<: *closed
    variables:
      name: *morbach
      notfall: *notfall
      opening-hours: >-
        <s>Diese sind von Montag bis Freitag von <say-as interpret-as="time">09:00</say-as> bis <say-as interpret-as="time">13:00</say-as>.</s>
        <s>Montags und Freitags haben wir zusätzlich von <say-as interpret-as="time">14:00</say-as> bis <say-as interpret-as="time">18:00</say-as> geöffnet.</s>
  'Thalfang-geschlossen':
    <<: *closed
    variables:
      name: *thalfang
      notfall: *notfall
      opening-hours: >-
        <s>Diese sind von Montag bis Freitag von <say-as interpret-as="time">09:00</say-as> bis <say-as interpret-as="time">13:00</say-as>.</s>
        <s>Dienstags und Donnerstags haben wir zusätzlich von <say-as interpret-as="time">14:00</say-as> bis <say-as interpret-as="time">18:00</say-as> geöffnet.</s>
  'Piesport-beschäftigt':
    <<: *busy
    variables:
      name: *piesport

  'Bernkastel-Kues-beschäftigt':
    <<: *busy
    variables:
      name: *bks
  'Morbach-beschäftigt':
    <<: *busy
    variables:
      name: *morbach
  'Thalfang-beschäftigt':
    <<: *busy
    variables:
      name: *thalfang

  'Morbach-nur-vormittags':
    <<: *krankheit-geschlossen
    variables:
      name: *morbach
      notfall: *notfall
  'Thalfang-nur-vormittags':
    <<: *krankheit-geschlossen
    variables:
      name: *thalfang
      notfall: *notfall
